# Generated by Django 6.0.4 on 2026-04-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="no_of_seats",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
