# Generated by Django 6.0.4 on 2026-04-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_bus_no_of_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="no_of_seats",
            field=models.PositiveBigIntegerField(),
        ),
    ]
